[project]
protostar-version = "0.9.0"
lib-path = "contracts/starknet/lib"
cairo-path = ["contracts/starknet/src", "contracts/starknet/lib", "contracts/starknet/lib/cairo_streams/src"]

[contracts]
Account = ["contracts/starknet/src/account/Account.cairo"]
Admin = ["contracts/starknet/src/admin/Admin.cairo"]
CheckEthThreshold = ["contracts/starknet/src/sample_consumer/CheckEthThreshold.cairo"]
Oracle = ["contracts/starknet/src/oracle/Oracle.cairo"]
Proxy = ["contracts/starknet/src/proxy/Proxy.cairo"]
PublisherRegistry = ["contracts/starknet/src/publisher_registry/PublisherRegistry.cairo"]
SummaryStats = ["contracts/starknet/src/compute_engines/summary_stats/SummaryStats.cairo"]
YieldCurve = ["contracts/starknet/src/compute_engines/yield_curve/YieldCurve.cairo"]
Randomness = ["contracts/starknet/src/randomness/Randomness.cairo"]
ExampleRandomness = ["contracts/starknet/src/randomness/ExampleRandomness.cairo"]

[build]
output = "contracts/starknet/build"

