["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "contracts/lib"

["protostar.contracts"]
Account = [
    "contracts/src/account/Account.cairo"
]
CheckEthThreshold = [
    "contracts/src/sample_consumer/CheckEthThreshold.cairo"
]
OracleController = [
    "contracts/src/oracle_controller/OracleController.cairo"
]
OracleImplementation = [
    "contracts/src/oracle_implementation/OracleImplementation.cairo"
]
PublisherRegistry = [
    "contracts/src/publisher_registry/PublisherRegistry.cairo"
]
YieldCurve = [
    "contracts/src/compute_engines/yield_curve/YieldCurve.cairo"
]

["protostar.shared_command_configs"]
cairo-path = ["contracts/src"]

["protostar.build"]
output = "contracts/build"
