["protostar.config"]
protostar_version = "0.3.2"
cairo-path = ["contracts/src"]

["protostar.project"]
libs_path = "contracts/src"

["protostar.contracts"]
Account = [
    "contracts/account/Account.cairo"
]
CheckEthThreshold = [
    "contracts/sample_consumer/CheckEthThreshold.cairo"
]
OracleController = [
    "contracts/oracle_controller/OracleController.cairo"
]
OracleImplementation = [
    "contracts/oracle_implementation/OracleImplementation.cairo"
]
PublisherRegistry = [
    "contracts/publisher_registry/PublisherRegistry.cairo"
]
YieldCurve = [
    "contracts/compute_engines/yield_curve/YieldCurve.cairo"
]

["protostar.build"]
output = "contracts/abi_test"
