name: Run test on integration net
on:
  workflow_dispatch:
  schedule:
    - cron: "40 6,18 * * *"

jobs:
  publish_and_consume_on_integration:
    name: Publish and get eth/usd price on integration net
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade --upgrade-strategy eager
          pip install -r dev-requirements.txt --upgrade --upgrade-strategy eager
          pip install -e empiric-package

      - name: Publish data
        env:
          PUBLISHER: empiric
          PUBLISHER_PRIVATE_KEY: ${{ secrets.INTEGRATION_PUBLISHER_PRIVATE_KEY }}
          PUBLISHER_ADDRESS: "3053905924911392281185613487163536321775910383295124523151415438844445678030"
          __EMPIRIC_PUBLISHER_EXIT_ON_ERROR__: TRUE
        run: python publisher/sample-publisher/integration/fetch-and-publish.py

      - name: Wait for transaction to be accepted
        run: sleep 300

      - name: Run sample client
        run: python sample_client.py --network https://external.integration.starknet.io
