name: Push Empiric Publisher Docker Image
on:
  push:
    branches:
      - master

jobs:
  push_empiric_publisher:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build and publish image
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          export $(grep -v '^#' .env | xargs)
          export EMPIRIC_PACKAGE_VERSION=$(grep 'version' empiric-package/setup.cfg | grep -e '[0-9]*\.[0-9]*\.[0-9]*' -o)
          docker build . --target production --build-arg EMPIRIC_PACKAGE_VERSION=${EMPIRIC_PACKAGE_VERSION} -t 42labs/empiric-publisher:${EMPIRIC_PACKAGE_VERSION}
          echo $DOCKER_ACCESS_TOKEN | docker login -u ${DOCKER_LOGIN} --password-stdin
          docker push 42labs/empiric-publisher:${EMPIRIC_PACKAGE_VERSION}
