name: Publish Empiric Package
on:
  push:
    branches:
      - master
      - fix-push-empiric-package

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.13"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Build and publish Python package
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python3 -m pip install --upgrade -r dev-requirements.txt
          cd empiric-package
          python3 -m build

      - name: Build and publish Docker image
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          export $(grep -v '^#' .env | xargs)
          export EMPIRIC_PACKAGE_VERSION=$(grep 'version' empiric-package/setup.cfg | grep -e '[0-9][0-9a-zA-Z]*[-.a-z0-9]*' -o)
          docker build . --target production --build-arg EMPIRIC_PACKAGE_VERSION=${EMPIRIC_PACKAGE_VERSION} -t 42labs/empiric-publisher:${EMPIRIC_PACKAGE_VERSION}
          echo $DOCKER_ACCESS_TOKEN | docker login -u ${DOCKER_LOGIN} --password-stdin
          docker push 42labs/empiric-publisher:${EMPIRIC_PACKAGE_VERSION}
