name: Run Monitors
on:
  push:
    branches:
      - master

jobs:
  run_monitors:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build docker images locally
        run: |
          docker build . --target test -t astralylabs/empiric-publisher:test
          docker build stagecoach/monitors/balance -f stagecoach/monitors/balance/Integration.Dockerfile -t monitor-balance --platform linux/amd64
          docker build stagecoach/monitors/price -f stagecoach/monitors/price/Integration.Dockerfile -t monitor-price --platform linux/amd64

      - name: Run balance and price monitors
        env:
          TELEGRAM_BOT_USER_OAUTH_TOKEN: ${{ secrets.TELEGRAM_BOT_USER_OAUTH_TOKEN }}
        run: |
          docker run --env-file stagecoach/monitors/balance/.env \
            -e TELEGRAM_BOT_USER_OAUTH_TOKEN=${TELEGRAM_BOT_USER_OAUTH_TOKEN} \
            -e NETWORK=testnet \
            monitor-balance
          docker run --env-file stagecoach/monitors/price/.env \
            -e TELEGRAM_BOT_USER_OAUTH_TOKEN=${TELEGRAM_BOT_USER_OAUTH_TOKEN} \
            -e NETWORK=testnet \
            -e MIN_NUM_SOURCES_AGGREGATED=3 \
            monitor-price
