name: Run Tests
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade --upgrade-strategy eager
          pip install -r dev-requirements.txt --upgrade --upgrade-strategy eager
          pip install -e empiric-package
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
          source /home/runner/.bashrc
          echo "$HOME/.protostar/dist/protostar" >> $GITHUB_PATH
          echo "$HOME/.protostar/dist/protostar" >> $PATH
          echo $HOME
          echo "$PATH"
          echo "$GITHUB_PATH"
          protostar --help

      - name: Format and lint
        run: |
          black . --check
          flake8 .
          isort . --check-only --diff
          cairo-format $(find contracts -name '*.cairo') -c

      - name: Check contract interface consistency
        run: |
          python -m empiric.test.interface_consistency --cairo-path 'contracts/src,contracts/lib'

      - name: Run tests suite
        run: |
          pytest .

      - name: Run protostar tests
        run: |
          source $HOME/.bashrc
          protostar test ./contracts/test
