name: Update Prices
on:
  push

jobs:
  update_prices:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build publisher images locally
        run: |
          docker build . -t 42labs/pontis-publisher:latest
          docker build sample-publisher/all/ -t publish-all --build-arg PONTIS_PUBLISHER_BASE_IMAGE_TAG=latest

      - name: Post updated prices
        env:
          PUBLISHER_PREFIX: pontis
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
          COINAPI_KEY: ${{ secrets.COINAPI_KEY }}
          COINAPI_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINAPI_PUBLISHER_PRIVATE_KEY }}
          COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY }}
          COINMARKETCAP_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINMARKETCAP_PUBLISHER_PRIVATE_KEY }}
          COINGECKO_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINGECKO_PUBLISHER_PRIVATE_KEY }}
          COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
          COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
          COINBASE_API_PASSPHRASE: ${{ secrets.COINBASE_API_PASSPHRASE }}
          COINBASE_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINBASE_PUBLISHER_PRIVATE_KEY }}
          GEMINI_PUBLISHER_PRIVATE_KEY: ${{ secrets.GEMINI_PUBLISHER_PRIVATE_KEY }}
          BINANCE_PUBLISHER_PRIVATE_KEY: ${{ secrets.BINANCE_PUBLISHER_PRIVATE_KEY }}
          FTX_API_KEY: ${{ secrets.FTX_API_KEY }}
          FTX_API_SECRET: ${{ secrets.FTX_API_SECRET }}
          FTX_PUBLISHER_PRIVATE_KEY: ${{ secrets.FTX_PUBLISHER_PRIVATE_KEY }}
        run: |
          docker run \
            -e ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}\
            -e COINAPI_KEY=${COINAPI_KEY}\
            -e COINAPI_PUBLISHER_PRIVATE_KEY=${COINAPI_PUBLISHER_PRIVATE_KEY}\
            -e COINMARKETCAP_KEY=${COINMARKETCAP_KEY}\
            -e COINMARKETCAP_PUBLISHER_PRIVATE_KEY=${COINMARKETCAP_PUBLISHER_PRIVATE_KEY}\
            -e COINGECKO_PUBLISHER_PRIVATE_KEY=${COINGECKO_PUBLISHER_PRIVATE_KEY}\
            -e COINBASE_API_SECRET=${COINBASE_API_SECRET}\
            -e COINBASE_API_KEY=${COINBASE_API_KEY}\
            -e COINBASE_API_PASSPHRASE=${COINBASE_API_PASSPHRASE}\
            -e COINBASE_PUBLISHER_PRIVATE_KEY=${COINBASE_PUBLISHER_PRIVATE_KEY}\
            -e GEMINI_PUBLISHER_PRIVATE_KEY=${GEMINI_PUBLISHER_PRIVATE_KEY}\
            -e BINANCE_PUBLISHER_PRIVATE_KEY=${BINANCE_PUBLISHER_PRIVATE_KEY}\
            -e FTX_API_KEY=${FTX_API_KEY}\
            -e FTX_API_SECRET=${FTX_API_SECRET}\
            -e FTX_PUBLISHER_PRIVATE_KEY=${FTX_PUBLISHER_PRIVATE_KEY}\
            publish-all

