name: Update Prices
on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  update_prices:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post updated prices
        env:
          COINAPI_KEY: ${{ secrets.COINAPI_KEY }}
          COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY }}
          COINAPI_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINAPI_PUBLISHER_PRIVATE_KEY }}
          COINMARKETCAP_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINMARKETCAP_PUBLISHER_PRIVATE_KEY }}
          COINGECKO_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINGECKO_PUBLISHER_PRIVATE_KEY }}
          COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
          COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
          COINBASE_API_PASSPHRASE: ${{ secrets.COINBASE_API_PASSPHRASE }}
          COINBASE_PUBLISHER_PRIVATE_KEY: ${{ secrets.COINBASE_PUBLISHER_PRIVATE_KEY }}
          PUBLISHER_REGISTRATION_PRIVATE_KEY: ${{ secrets.PUBLISHER_REGISTRATION_PRIVATE_KEY }}
        run: |
          export $(grep -v '^#' .env | xargs)
          python publisher.py
