name: Update Prices
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environmental variables
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Post updated prices
        env:
          COINAPI_KEY: ${{ secrets.COINAPI_KEY }}
          PRIVATE_PUBLISHER_KEY: ${{ secrets.PRIVATE_PUBLISHER_KEY }}
        run: |
          python publisher.py
