name: Update Prices
on:
  push

jobs:
  update_prices:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build publisher images locally
        run: |
          docker build . --target test -t 42labs/pontis-publisher:test
          docker build publisher/sample-publisher/all/ -t publish-all --build-arg PONTIS_PUBLISHER_BASE_IMAGE_TAG=test

      - name: Post updated prices
        env:
          __PONTIS_STAGING_ENV__: "TRUE"
          PUBLISHER_ADDRESS: "3251373723367219268498787183941698604007480963314075130334762142902855469511"
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
          PUBLISHER_PRIVATE_KEY : ${{ secrets.PUBLISHER_PRIVATE_KEY }}
          COINAPI_KEY: ${{ secrets.COINAPI_KEY }}
          COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY }}
          COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
          COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
          COINBASE_API_PASSPHRASE: ${{ secrets.COINBASE_API_PASSPHRASE }}
          FTX_API_KEY: ${{ secrets.FTX_API_KEY }}
          FTX_API_SECRET: ${{ secrets.FTX_API_SECRET }}
        run: |
          docker run \
            --env-file publisher/sample-publisher/all/.env\
            -e __PONTIS_STAGING_ENV__=${__PONTIS_STAGING_ENV__}\
            -e PUBLISHER_ADDRESS=${PUBLISHER_ADDRESS}\
            -e ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}\
            -e PUBLISHER_PRIVATE_KEY=${PUBLISHER_PRIVATE_KEY}\
            -e COINAPI_KEY=${COINAPI_KEY}\
            -e COINMARKETCAP_KEY=${COINMARKETCAP_KEY}\
            -e COINBASE_API_SECRET=${COINBASE_API_SECRET}\
            -e COINBASE_API_KEY=${COINBASE_API_KEY}\
            -e COINBASE_API_PASSPHRASE=${COINBASE_API_PASSPHRASE}\
            -e FTX_API_KEY=${FTX_API_KEY}\
            -e FTX_API_SECRET=${FTX_API_SECRET}\
            publish-all

