name: Update Prices
on:
  push:
    branches:
      - master

jobs:
  update_prices:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build publisher images locally
        run: |
          docker build . --target test -t astralylabs/empiric-publisher:test
          docker build stagecoach/integration_tests/publish-all/ -t publish-all --platform linux/amd64
          docker build stagecoach/integration_tests/coinbase/ -t publish-coinbase --platform linux/amd64

      - name: Post updated prices
        env:
          PUBLISHER_PRIVATE_KEY: ${{ secrets.PUBLISHER_PRIVATE_KEY }}
        run: |
          docker run \
            --env-file stagecoach/integration_tests/publish-all/.env \
            -e __EMPIRIC_STAGING_ENV__=TRUE\
            -e __EMPIRIC_PUBLISHER_EXIT_ON_ERROR__=TRUE\
            -e NETWORK=testnet2\
            -e PUBLISHER_PRIVATE_KEY=${PUBLISHER_PRIVATE_KEY}\
            publish-all
          docker run \
            --env-file stagecoach/integration_tests/coinbase/.env \
            -e __EMPIRIC_STAGING_ENV__=TRUE\
            -e PUBLISHER_PRIVATE_KEY=${PUBLISHER_PRIVATE_KEY}\
            -e NETWORK=testnet2\
            publish-coinbase
